const category = {
    'income': [{
        'id': '1',
        'name': '工资薪水',
        'orderno': 1,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': null,
        'preset': 'SYSTEM'
    }, {
        'id': '6',
        'name': '利息',
        'orderno': 2,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': null,
        'preset': 'SYSTEM'
    }, {
        'id': '2',
        'name': '兼职外快',
        'orderno': 3,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': null,
        'preset': 'SYSTEM'
    }, {
        'id': '22',
        'name': '营业收入',
        'orderno': 4,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': 1414412481000,
        'preset': 'SYSTEM'
    }, {
        'id': '19',
        'name': '红包',
        'orderno': 5,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': 1414412481000,
        'preset': 'SYSTEM'
    }, {
        'id': '12',
        'name': '销售款',
        'orderno': 6,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': null,
        'preset': 'SYSTEM'
    }, {
        'id': '18',
        'name': '退款返款',
        'orderno': 7,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': 1414412481000,
        'preset': 'SYSTEM'
    }, {
        'id': '14',
        'name': '报销款',
        'orderno': 8,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': 1311149118000,
        'preset': 'SYSTEM'
    }, {
        'id': '8',
        'name': '福利补贴',
        'orderno': 9,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': null,
        'preset': 'SYSTEM'
    }, {
        'id': '21',
        'name': '余额宝',
        'orderno': 10,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': 1414412481000,
        'preset': 'SYSTEM'
    }, {
        'id': '11',
        'name': '应收款',
        'orderno': 11,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': null,
        'preset': 'SYSTEM'
    }, {
        'id': '16',
        'name': '生活费',
        'orderno': 12,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': 1414412481000,
        'preset': 'SYSTEM'
    }, {
        'id': '7',
        'name': '奖金',
        'orderno': 13,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': null,
        'preset': 'SYSTEM'
    }, {
        'id': '4',
        'name': '基金',
        'orderno': 14,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': null,
        'preset': 'SYSTEM'
    }, {
        'id': '9',
        'name': '礼金',
        'orderno': 15,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': null,
        'preset': 'SYSTEM'
    }, {
        'id': '5',
        'name': '分红',
        'orderno': 16,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': null,
        'preset': 'SYSTEM'
    }, {
        'id': '10',
        'name': '租金',
        'orderno': 17,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': null,
        'preset': 'SYSTEM'
    }, {
        'id': '3',
        'name': '股票',
        'orderno': 18,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': null,
        'preset': 'SYSTEM'
    }, {
        'id': '17',
        'name': '公积金',
        'orderno': 19,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': 1414412481000,
        'preset': 'SYSTEM'
    }, {
        'id': '23',
        'name': '工程款',
        'orderno': 20,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': 1414412481000,
        'preset': 'SYSTEM'
    }, {
        'id': '20',
        'name': '赔付款',
        'orderno': 21,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': 1414412481000,
        'preset': 'SYSTEM'
    }, {
        'id': '15',
        'name': '漏记款',
        'orderno': 22,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': 1354086000000,
        'preset': 'SYSTEM'
    }, {
        'id': '13',
        'name': '其他',
        'orderno': 23,
        'lastModTime': 1513306286000,
        'userId': null,
        'enable': 1,
        'bookType': 1,
        'createTime': null,
        'preset': 'SYSTEM'
    }],
    'outgo': [{
        'id': '10',
        'name': '餐饮',
        'subtype': [{
            'id': '1001',
            'name': '早餐'
        }, {
            'id': '1002',
            'name': '午餐'
        }, {
            'id': '1003',
            'name': '晚餐'
        }, {
            'id': '1004',
            'name': '夜宵'
        }, {
            'id': '1008',
            'name': '零食'
        }, {
            'id': '1005',
            'name': '饮料水果'
        }, {
            'id': '1006',
            'name': '买菜原料'
        }, {
            'id': '1009',
            'name': '油盐酱醋'
        }, {
            'id': '1007',
            'name': '餐饮其他'
        }]
    }, {
        'id': '11',
        'name': '交通',
        'subtype': [{
            'id': '1101',
            'name': '打车'
        }, {
            'id': '1102',
            'name': '公交'
        }, {
            'id': '1104',
            'name': '加油'
        }, {
            'id': '1105',
            'name': '停车费'
        }, {
            'id': '1103',
            'name': '地铁'
        }, {
            'id': '1109',
            'name': '火车'
        }, {
            'id': '1117',
            'name': '长途汽车'
        }, {
            'id': '1111',
            'name': '飞机'
        }, {
            'id': '1113',
            'name': '自行车'
        }, {
            'id': '1112',
            'name': '船舶'
        }, {
            'id': '1108',
            'name': '保养维修'
        }, {
            'id': '1106',
            'name': '过路过桥'
        }, {
            'id': '1107',
            'name': '罚款赔偿'
        }, {
            'id': '1110',
            'name': '车款车贷'
        }, {
            'id': '1115',
            'name': '车险'
        }, {
            'id': '1116',
            'name': '驾照费用'
        }, {
            'id': '1114',
            'name': '交通其他'
        }]
    }, {
        'id': '12',
        'name': '购物',
        'subtype': [{
            'id': '1201',
            'name': '服饰鞋包'
        }, {
            'id': '1202',
            'name': '家居百货'
        }, {
            'id': '1212',
            'name': '宝宝用品'
        }, {
            'id': '1204',
            'name': '化妆护肤'
        }, {
            'id': '1211',
            'name': '烟酒'
        }, {
            'id': '1203',
            'name': '电子数码'
        }, {
            'id': '1209',
            'name': '文具玩具'
        }, {
            'id': '1208',
            'name': '报刊书籍'
        }, {
            'id': '1205',
            'name': '珠宝首饰'
        }, {
            'id': '1207',
            'name': '家具家纺'
        }, {
            'id': '1213',
            'name': '保健用品'
        }, {
            'id': '1206',
            'name': '电器'
        }, {
            'id': '1214',
            'name': '摄影文印'
        }, {
            'id': '1210',
            'name': '购物其他'
        }]
    }, {
        'id': '13',
        'name': '娱乐',
        'subtype': [{
            'id': '1308',
            'name': '旅游度假'
        }, {
            'id': '1302',
            'name': '电影'
        }, {
            'id': '1304',
            'name': '网游电玩'
        }, {
            'id': '1312',
            'name': '麻将棋牌'
        }, {
            'id': '1306',
            'name': '洗浴足浴'
        }, {
            'id': '1305',
            'name': '运动健身'
        }, {
            'id': '1311',
            'name': '花鸟宠物'
        }, {
            'id': '1313',
            'name': '聚会玩乐'
        }, {
            'id': '1307',
            'name': '茶酒咖啡'
        }, {
            'id': '1301',
            'name': '卡拉OK'
        }, {
            'id': '1309',
            'name': '歌舞演出'
        }, {
            'id': '1303',
            'name': '电视'
        }, {
            'id': '1310',
            'name': '娱乐其他'
        }]
    }, {
        'id': '14',
        'name': '医教',
        'subtype': [{
            'id': '1401',
            'name': '医疗药品'
        }, {
            'id': '1407',
            'name': '挂号门诊'
        }, {
            'id': '1408',
            'name': '养生保健'
        }, {
            'id': '1409',
            'name': '住院费'
        }, {
            'id': '1410',
            'name': '养老院'
        }, {
            'id': '1403',
            'name': '学杂教材'
        }, {
            'id': '1402',
            'name': '培训考试'
        }, {
            'id': '1412',
            'name': '幼儿教育'
        }, {
            'id': '1411',
            'name': '学费'
        }, {
            'id': '1406',
            'name': '家教补习'
        }, {
            'id': '1413',
            'name': '出国留学'
        }, {
            'id': '1405',
            'name': '助学贷款'
        }, {
            'id': '1404',
            'name': '医教其他'
        }]
    }, {
        'id': '15',
        'name': '居家',
        'subtype': [{
            'id': '1501',
            'name': '手机电话'
        }, {
            'id': '1504',
            'name': '水电燃气'
        }, {
            'id': '1517',
            'name': '生活费'
        }, {
            'id': '1511',
            'name': '美发美容'
        }, {
            'id': '1506',
            'name': '住宿房租'
        }, {
            'id': '1507',
            'name': '材料建材'
        }, {
            'id': '1503',
            'name': '房款房贷'
        }, {
            'id': '1509',
            'name': '快递邮政'
        }, {
            'id': '1502',
            'name': '电脑宽带'
        }, {
            'id': '1508',
            'name': '家政服务'
        }, {
            'id': '1505',
            'name': '物业'
        }, {
            'id': '1514',
            'name': '税费手续费'
        }, {
            'id': '1512',
            'name': '保险费'
        }, {
            'id': '1513',
            'name': '消费贷款'
        }, {
            'id': '1516',
            'name': '婚庆摄影'
        }, {
            'id': '1515',
            'name': '漏记款'
        }, {
            'id': '1510',
            'name': '生活其他'
        }]
    }, {
        'id': '16',
        'name': '投资',
        'subtype': [{
            'id': '1610',
            'name': '利息支出'
        }, {
            'id': '1602',
            'name': '保险'
        }, {
            'id': '1603',
            'name': '出资'
        }, {
            'id': '1611',
            'name': '基金'
        }, {
            'id': '1616',
            'name': '股票'
        }, {
            'id': '1612',
            'name': 'P2P'
        }, {
            'id': '1615',
            'name': '余额宝'
        }, {
            'id': '1614',
            'name': '理财产品'
        }, {
            'id': '1606',
            'name': '投资贷款'
        }, {
            'id': '1613',
            'name': '银行存款'
        }, {
            'id': '1601',
            'name': '证券期货'
        }, {
            'id': '1607',
            'name': '外汇'
        }, {
            'id': '1604',
            'name': '贵金属'
        }, {
            'id': '1608',
            'name': '收藏品'
        }, {
            'id': '1605',
            'name': '投资其他'
        }]
    }, {
        'id': '17',
        'name': '人情',
        'subtype': [{
            'id': '1701',
            'name': '礼金红包'
        }, {
            'id': '1702',
            'name': '物品'
        }, {
            'id': '1708',
            'name': '孝敬'
        }, {
            'id': '1707',
            'name': '请客'
        }, {
            'id': '1709',
            'name': '给予'
        }, {
            'id': '1704',
            'name': '代付款'
        }, {
            'id': '1703',
            'name': '慈善捐款'
        }, {
            'id': '1705',
            'name': '人情其他'
        }]
    }, {
        'id': '18',
        'name': '生意',
        'subtype': [{
            'id': '1801',
            'name': '进货采购'
        }, {
            'id': '1802',
            'name': '人工支出'
        }, {
            'id': '1803',
            'name': '材料辅料'
        }, {
            'id': '1808',
            'name': '办公费用'
        }, {
            'id': '1805',
            'name': '交通运输'
        }, {
            'id': '1804',
            'name': '工程付款'
        }, {
            'id': '1806',
            'name': '运营费'
        }, {
            'id': '1807',
            'name': '会务费'
        }, {
            'id': '1809',
            'name': '营销广告'
        }, {
            'id': '1810',
            'name': '店面租金'
        }, {
            'id': '1811',
            'name': '注册登记'
        }, {
            'id': '1812',
            'name': '生意其他'
        }]
    }]
};

module.exports = {
    category,
};